
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: MineBlock 玩家手册
nav:
  - 主页: index.md
  - 规则:
    - MineBlock 玩家守则: rules/server-rules.md
    - 在 MineBlock 上使用模组的规则: rules/allowed-modifications.md
  - 玩法和机制:
    - mechanism/index.md
    - 负魔书: 
      - mechanism/DeEnchantment/index.md
      - 负魔列表: mechanism/DeEnchantment/enchantment-list.md
    - 城镇: 
      - mechanism/Towny/index.md
      - 命令: mechanism/Towny/command.md
  - 服务器内容:
    - 特权表: server/rank.md
    - 已知 Bug: server/bugs.md
    - 隐私政策: server/privacy.md
theme:
  name: material
  #custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  font:
    text: Roboto
    code: Roboto Mono
  favicon: https://mineblock.gitee.io/favicon.ico
  icon:
    logo: material/library
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
repo_url: https://github.com/MineBlockMC/MineBlock-Book
repo_name: MineBlock-Book
edit_uri: edit/mkdocs/docs/
markdown_extensions:
  - admonition
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      fallback_to_build_date: true